library(readr)
emp_data<-read.csv(file.choose())
View(emp_data)
colnames(emp_data)
attach(emp_data)
library(moments)
hist(Salary_hike)
hist(Churn_out_rate)
skewness(Salary_hike)
skewness(Churn_out_rate)
qqline(Salary_hike)
qqnorm(Salary_hike)
qqline(Churn_out_rate)
qqnorm(Churn_out_rate)
plot(Salary_hike)
boxplot(Salary_hike)
boxplot(Churn_out_rate)
cor.test(Salary_hike,Churn_out_rate)
model1<-lm(Churn_out_rate~Salary_hike,data=emp_data)
summary(model1)
library(caTools)
split<-sample.split(Churn_out_rate,SplitRatio = 0.7)
train<-subset(emp_data,split==TRUE)
test<-subset(emp_data,split==FALSE)
model3<-lm(Churn_out_rate~Salary_hike,data = train)
summary(model3)
errortrain<-train$Churn_out_rate-model3$fitted.values
rmsetrain<-sqrt(mean(errortrain^2))
pred_test<-predict(model3,newdata = test)
errortest<-test$Churn_out_rate-pred_test
rmsetest<-sqrt(mean(errortest^2))
print(c(rmsetrain,rmsetest))
