library(readr)
computer<-read.csv(file.choose())
View(computer)
str(computer)
summary(computer)
colnames(computer)
attach(computer)
hist(price)
hist(speed)
hist(hd)
hist(ram)
hist(screen)
boxplot(price)
boxplot(speed)
boxplot(hd)
boxplot(ram)
boxplot(screen)
cor.test(price,speed)
cor.test(price,hd)
cor.test(price,hd)
cor.test(price,ram)
cor.test(price,screen)
library(moments)
skewness(price)
skewness(speed)
skewness(hd)
skewness(ram)
skewness(screen)
qnorm(price)
sum(is.na(computer))
model1<-lm(price~., data=computer)
summary(model1)
library(caTools)
data_split<-sample.split(computer, SplitRatio = 0.7)
test<-subset(computer,data_split=TRUE)
train<-subset(computer, data_split=FALSE)
model2<-lm(price~.,data=train)
summary(model2)
errortrain<-train$price-model2$fitted.values
rmsetrain<-sqrt(mean(errortrain)^2)
predtest<-predict(model2, data=test)
errotest<-test$price-predtest
rmsetest<-sqrt(mean(errotest)^2)
print(c(rmsetest,rmsetrain))
