 library(readr)
install.packages("recommenderlab", dependencies=TRUE)
install.packages("Matrix")
library(readr)
library(recommenderlab)
library(caTools)
library(readr)
books<-read.csv(file.choose())
View(books)
books1<-books[,3:6]
View(books1)
books_matr<-as(books1,"realRatingMatrix")
model1<-Recommender(books_matr, method="popular")
recommeded_item1<-predict(model1,books_matr[1166],n=6)
as(recommeded_item1,"list")
