library(readr)
library(moments)
library(caTools)
salarydata<-read.csv(file.choose())
attach(salarydata)
hist(salarydata$YearsExperience)
hist(salarydata$Salary)
skewness(Salary)i
skewness(YearsExperience)
boxplot(Salary)
boxplot(YearsExperience)
qqnorm(Salary)
qqline(Salary)
qqnorm(YearsExperience)
qqline(YearsExperience)
cor.test(YearsExperience,Salary)
model<-lm(YearsExperience~Salary,data=salarydata)
summary(model)
split<-sample.split(salarydata$YearsExperience, SplitRatio = 0.6)
train=subset(salarydata$YearsExperience,split==TRUE)
test=subset(salarydata$YearsExperience,split==FALSE)
model_train<-lm(salarydata$YearsExperience~salarydata$Salary, data=train)

